### ISSUE TITLE
Unhelpful error when test files are missing from `auto_test_dir`

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/mrgvalidate#76]
This was reported by @mgboyd1024 when trying to run `create_validation_docs()` and accidentally passing an empty directory to the `auto_test_dir` argument:

![image (3)](https://user-images.githubusercontent.com/7806083/144480719-db520419-bb1c-4996-b927-4f22f2b037ee.png)

We should probably do better than `Error: .x is empty...` in that situation.

In reality, all the `_dir` arguments should probably get checked and the user informatively warned (or maybe an actual error?) if they pass an empty directory to one of those arguments. Or probably even if they pass a directory that has none of the kinds of files we're looking for (which is different depending on which `_dir` argument we're talking about).

**Comment by kyleam** [comment]
> accidentally passing an empty directory to the `auto_test_dir` argument

Odd.  Haven't tried myself yet, but I would have expected an empty directory to hit into this error:

https://github.com/metrumresearchgroup/mrgvalidate/blob/0d22a0ce7889481c5a8698c53a1bd36f3d84c78f/R/read-results.R#L14-L20


> the user informatively warned (or maybe an actual error?)
> [...] Or probably even if they pass a directory that has none of the kinds of files we're looking for

Aborting in these cases sounds like the way to go to me (and is line with already existing errors like the one above and elsewhere).

**Comment by kyleam** [comment]
Or perhaps this was with an older version?  

v1.0.1 included 0353932 (fix: read_csv_test_results: give informative "no CSVs found" error, 2021-08-17) and the error reported here matches the one I described in the commit message:

```
fix: read_csv_test_results: give informative "no CSVs found" error

If read_csv_test_results() is passed a directory that doesn't have any
CSV files, it fails with an unhelpful

   `.x` is empty, and no `.init` supplied

Provide a better error message.
```

**Comment by seth127** [comment]
ahhhhh, that's probably right. @mgboyd1024 can you confirm what version of `mrgvalidate` you were using? Run `packageVersion("mrgvalidate")` from within that R session. Thanks.

**Comment by mgboyd1024** [comment]
Hey guys,
The mrgvalidate package version is 1.0.0

![image](https://user-images.githubusercontent.com/92536416/144872915-297658a7-770e-49a4-ad5c-ddce0591fa6d.png)

**Comment by kyleam** [comment]
Thanks @mgboyd1024.  So indeed it looks like you were running on a version without the above fix.  `man_test_dir` has a similar check (added in the same pr, gh-64), so I think we should be covered.  

@seth127, I'll close this, but please reopen if you think there's anything else to look into or do.
