### ISSUE TITLE
New feature: story id's column in traceability matrix

### ISSUE THREAD

**Issue by tkwilos** [metrumresearchgroup/mrgvalidate#82]
Request stems from an audit finding: can we change the format of the Traceability Matrix, adding a column with the Story ID at the start (to go with the story itself, and then the associated test ids)?

<img width="629" alt="image" src="https://user-images.githubusercontent.com/67168516/183785645-9e5d0cea-9b2f-4693-ae22-e3873212f9d4.png">

**Comment by barrettk** [comment]
@tkwilos Just added this [fix](https://github.com/metrumresearchgroup/mrgvalidate/pull/80/commits/90f25fc2040d2394a57710ca163888c943e6db10). I made this the case for both packages and metworx docs. @seth127 tagging you in case we only want this to be for metworx docs

**Comment by barrettk** [comment]
### Documenting options here:
![image](https://user-images.githubusercontent.com/18685116/185985367-6a5a9524-d591-4d8e-acfb-0345bef40287.png)

#### From an email with Aing:
![image](https://user-images.githubusercontent.com/18685116/185985509-be3613a6-7d57-4570-afbc-869c55a5fd8e.png)
