### ISSUE TITLE
Add Go option for `create_package_docs()`

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/mrgvalidate#83]
The new documentation created by `create_package_docs()` (as of #80) mostly works for Go packages the same as R packages, except for one section in the Testing Plan document which mentions `testthat`. We need to have an interface for replacing that with:

> Testing in both development and validation phases proceeded using a standardized, automated unit testing framework via Go’s standard testing framework. Tests were written in Go and saved to `.go` source files with the suffix `_test` located within the bbi repository.  Testing was executed using the `go test ./...` command which ran all tests in every test file in the repository. The test results are captured as a `.json` file  and saved as an artifact from the validation testing. Tests relevant to the user stories covered by this change request were extracted from the larger test matrix to create the traceability matrix connecting the user story with the test result. 

I don't think there are any other deviations, but we should look a bit more to make sure.

**Comment by barrettk** [comment]
@seth127 do we want to have `bbi` in this text? I feel like we should make this more general, so we could use it for other `go` packages as well

**Comment by seth127** [comment]
yep, good catch. It should be generic, so that sentence can just be

> ...located within the repository.

**Comment by seth127** [comment]
Closed by #85
