### ISSUE TITLE
[Bug] quotation marks not handled properly in document rendering

### ISSUE THREAD

**Issue by tkwilos** [metrumresearchgroup/mrgvalidate#95]
Quotation marks are represented by `&quot;` in document rendering 

<img width="654" alt="image" src="https://user-images.githubusercontent.com/67168516/206862843-fc385ba2-8ca8-4677-bbb9-e99c24196a17.png">

**Comment by barrettk** [comment]
Closing since we couldnt reproduce and Tim left
